import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/component/header";
import Footer from "@/components/component/footer";
import { SessionProvider } from "next-auth/react";
import { GoogleAnalytics  } from '@next/third-parties/google';
 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Header />
          <SessionProvider>
            {children}
          </SessionProvider>
          <Footer />
        </div>
      </body>
      <GoogleAnalytics  gaId={process.env.NEXT_PUBLIC_GA_ID || ""} />
    </html>
  );
}
